version: "3"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/php/8.2/Dockerfile
        image: home/php-app
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/8.2/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/8.2/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/8.2/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
            - "9000:9000"
        networks:
            - app-network
    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        depends_on:
            - app
        tty: true
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
